### PR TITLE
added new social media platform to the code 

### PR DESCRIPTION
**Pull request by aromatic-toast**
# What changed 
- added `AllTrails` to the front and backend to display alltrails data. 

@woodsp, 
Do you have any suggestions for a color for `alltrails`? The screenshot below shows what it is currently set to. But can easily change this if you are thinking a different color would look better. 

Screen Shot 2020-09-14 at 1 53 00 PM

### CODE REVIEW

**Comment by sgwinder** [comment]
I like the teal!

**Review by vivekkr12 — APPROVED** [review]
Looks good to me!

**Comment by aromatic-toast** [comment]
@sgwinder, 
Yeah i kind of agree about the legend. This is how the code is originally set up. My intuition is that this is to differentiate between charts showing data for ALL polygons aggregated together vs data for specific polygon when a polygon gets selected. Perhaps there are other ways to implement the label, though.

**Comment by woodsp** [comment]
Teal looks good to me too, but I'm not colorblind.  If this isn't colorblind-safe, then it would be wise to get a palette from [colorbrewer](https://colorbrewer2.org)

**Comment by sgwinder** [comment]
It looks like this color scheme is actually pretty good for colorblindness - I pasted it into the [color blindness simulator](https://www.color-blindness.com/coblis-color-blindness-simulator/) and it looked good for all the common types except complete colorblindness (Monochromacy).

image

As a heads up, colorbrewer palettes aren't all colorblind-friendly either. [Viridis](https://www.thinkingondata.com/something-about-viridis-library/) is the most popular colorblind palette that I know of, though it seems to be built for R. Their palettes are also continuous, meaning that the discrete options aren't always great.

**Pull request merged**
